name: General Workflow

on:
  push:
    branches:
      - main
    paths:
      - "rust_lambda/**"
      - "infrastructure/**"
      - ".github/workflows/general.yml"
      - ".github/workflows/pull_request_code.yml"
      - ".github/workflows/pull_request_infrastructure.yml"

jobs:
  build_code:
    runs-on: ubuntu-latest
    services:
      dynamodb:
        image: amazon/dynamodb-local
        ports:
          - 8000:8000
    defaults:
      run:
        working-directory: rust_lambda
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install the Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy, llvm-tools-preview
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Add host to /etc/hosts
        run: sudo echo "127.0.0.1 dynamodb" | sudo tee -a /etc/hosts
      - name: Enforce formatting
        run: cargo fmt --check
      - name: Linting
        run: cargo clippy -- -D warnings
      - name: Run tests
        run: cargo test
      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
      - name: Generate report
        run: cargo llvm-cov report --html --output-dir coverage
      - uses: actions/upload-artifact@v4
        with:
          name: "Coverage report"
          path: rust_lambda/coverage/
  build_infrastructure:
    runs-on: ubuntu-latest
    needs: [build_code]
    defaults:
      run:
        working-directory: infrastructure
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Node JS
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm ci
      - name: Build infrastructure
        run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: cdk.out
          path: infrastructure/cdk.out
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs: [build_code, build_infrastructure]
    defaults:
      run:
        working-directory: infrastructure
    concurrency: ${{ github.workflow }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: cdk.out
          path: infrastructure/cdk.out
      - name: Install Node JS
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm ci
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_GITHUB_ACTIONS_ROLE }}
          aws-region: ${{ vars.AWS_TARGET_REGION }}
      - name: deploy
        run: npm run deploy
