name: General Workflow

on:
  push:
    branches:
      - main
    paths:
      - "rust_lambda/**"
      - "infrastructure/**"
      - ".github/workflows/code.yml"
      - ".github/workflows/pull_request_code.yml"
      - ".github/workflows/pull_request_infrastructure.yml"

jobs:
  build_code:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install the Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy, llvm-tools-preview
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Enforce formatting
        run: cargo fmt --check
      - name: Linting
        run: cargo clippy -- -D warnings
      - name: Run tests
        run: cargo test
      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
      - name: Generate report
        run: cargo llvm-cov report --html --output-dir coverage
      - uses: actions/upload-artifact@v4
        with:
          name: "Coverage report"
          path: coverage/

      - uses: actions/upload-artifact@v4
        with:
          name: cdk.out
          path: infrastructure/cdk.out
  build_infrastructure:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build infrastructure
        run: npm run build
      - uses: actions/download-artifact@v4
        with:
          name: cdk.out
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs: [build_code, build_infrastructure]
    environment: integration
    concurrency: ${{ github.workflow }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: cdk.out
          path: infrastructure/cdk.out
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        working-directory: infrastructure
        run: npm ci
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_GITHUB_ACTIONS_ROLE }}
          aws-region: ${{ vars.AWS_TARGET_REGION }}
          role-session-name: "GitHubActions-DeployLayerStack"
      - name: deploy
        working-directory: infrastructure
        run: npm run deploy
